import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateFaqsTable1769409268147 implements MigrationInterface {
    name = 'CreateFaqsTable1769409268147'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_26daf5e433d6fb88ee32ce93637"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "fk_payments_service_request"`);
        await queryRunner.query(`ALTER TABLE "service_requests" DROP CONSTRAINT "fk_service_requests_payment"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_refresh_tokens_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_refresh_tokens_token"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_refresh_tokens_is_revoked"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea238a6937c1ab144a3820c737"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_service_request_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_stripe_payment_intent_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_subscriptions_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_subscriptions_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_subscriptions_plan_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_subscriptions_start_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_subscriptions_end_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_subscriptions_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_role_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_documents_service_request_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_documents_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_documents_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_service_requests_payment_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_service_requests_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_service_requests_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_service_requests_priority"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_service_requests_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_service_requests_assigned_operator_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_service_requests_service_type_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_service_requests_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_appointments_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_appointments_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_appointments_appointment_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_appointments_operator_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_is_read"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_user_read"`);
        await queryRunner.query(`CREATE TABLE "faqs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "service_type_id" uuid, "question" character varying(500) NOT NULL, "answer" text NOT NULL, "order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "category" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2ddf4f2c910f8e8fa2663a67bf0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`COMMENT ON COLUMN "invoices"."status" IS NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`COMMENT ON COLUMN "service_requests"."status" IS NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "notes" jsonb DEFAULT '{}'`);
        await queryRunner.query(`COMMENT ON COLUMN "service_types"."document_requirements" IS NULL`);
        await queryRunner.query(`ALTER TABLE "modello_730_requests" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "modello_730_requests" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "isee_requests" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "isee_requests" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "imu_requests" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "imu_requests" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "resource" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "action" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_26daf5e433d6fb88ee32ce93637" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_ea105d195b7ecd60a22771b3d59" FOREIGN KEY ("service_request_id") REFERENCES "service_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_requests" ADD CONSTRAINT "FK_cb2727a8a47a7f4224bb3f3ac74" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "faqs" ADD CONSTRAINT "FK_dd07a4286c605fd1fb1dc2fcd17" FOREIGN KEY ("service_type_id") REFERENCES "service_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`CREATE TABLE "query_result_cache" ("id" SERIAL NOT NULL, "identifier" character varying, "time" bigint NOT NULL, "duration" integer NOT NULL, "query" text NOT NULL, "result" text NOT NULL, CONSTRAINT "PK_2bfde1a0c552566e1992b3d0642" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "query_result_cache"`);
        await queryRunner.query(`ALTER TABLE "faqs" DROP CONSTRAINT "FK_dd07a4286c605fd1fb1dc2fcd17"`);
        await queryRunner.query(`ALTER TABLE "service_requests" DROP CONSTRAINT "FK_cb2727a8a47a7f4224bb3f3ac74"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_ea105d195b7ecd60a22771b3d59"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_26daf5e433d6fb88ee32ce93637"`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "action" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "resource" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "imu_requests" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "imu_requests" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "isee_requests" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "isee_requests" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "modello_730_requests" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "modello_730_requests" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "service_types"."document_requirements" IS 'Detailed document requirements with validation rules'`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "notes" text`);
        await queryRunner.query(`COMMENT ON COLUMN "service_requests"."status" IS 'Possible values: payment_pending, awaiting_form, awaiting_documents, draft, submitted, in_review, in_progress, missing_documents, completed, rejected'`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "invoices"."status" IS 'draft | sent | paid | void | uncollectible'`);
        await queryRunner.query(`DROP TABLE "faqs"`);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_user_read" ON "notifications" ("is_read", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_created_at" ON "notifications" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_user_id" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_is_read" ON "notifications" ("is_read") `);
        await queryRunner.query(`CREATE INDEX "IDX_appointments_operator_id" ON "appointments" ("operator_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_appointments_appointment_date" ON "appointments" ("appointment_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_appointments_status" ON "appointments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_appointments_user_id" ON "appointments" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_service_requests_user_status" ON "service_requests" ("status", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_service_requests_service_type_id" ON "service_requests" ("service_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_service_requests_assigned_operator_id" ON "service_requests" ("assigned_operator_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_service_requests_created_at" ON "service_requests" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_service_requests_priority" ON "service_requests" ("priority") `);
        await queryRunner.query(`CREATE INDEX "IDX_service_requests_status" ON "service_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_service_requests_user_id" ON "service_requests" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_service_requests_payment_id" ON "service_requests" ("payment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_documents_category" ON "documents" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_documents_status" ON "documents" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_documents_service_request_id" ON "documents" ("service_request_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_created_at" ON "users" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_is_active" ON "users" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_role_id" ON "users" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_subscriptions_user_status" ON "user_subscriptions" ("status", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_subscriptions_end_date" ON "user_subscriptions" ("end_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_subscriptions_start_date" ON "user_subscriptions" ("start_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_subscriptions_plan_id" ON "user_subscriptions" ("plan_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_subscriptions_status" ON "user_subscriptions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_subscriptions_user_id" ON "user_subscriptions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_stripe_payment_intent_id" ON "payments" ("stripe_payment_intent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_created_at" ON "payments" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_status" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_user_id" ON "payments" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_service_request_id" ON "payments" ("service_request_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ea238a6937c1ab144a3820c737" ON "invoices" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_refresh_tokens_is_revoked" ON "refresh_tokens" ("is_revoked") `);
        await queryRunner.query(`CREATE INDEX "IDX_refresh_tokens_token" ON "refresh_tokens" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_refresh_tokens_user_id" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "service_requests" ADD CONSTRAINT "fk_service_requests_payment" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "fk_payments_service_request" FOREIGN KEY ("service_request_id") REFERENCES "service_requests"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_26daf5e433d6fb88ee32ce93637" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
