// Form schemas for all services based on DATA.md requirements
// Every service includes comprehensive personal information section

const PERSONAL_INFORMATION_SECTION = {
  id: 'personal_information',
  title: 'Informazioni Personali',
  description: 'Your personal and contact information',
  fields: [
    {
      name: 'name',
      label: 'First Name',
      type: 'text',
      required: true,
      order: 1,
      maxLength: 100,
    },
    {
      name: 'surname',
      label: 'Surname',
      type: 'text',
      required: false,
      order: 2,
      maxLength: 100,
    },
    {
      name: 'email',
      label: 'Email',
      type: 'email',
      required: true,
      order: 3,
    },
    {
      name: 'mobile_phone_number',
      label: 'Mobile Phone Number',
      type: 'group',
      required: false,
      order: 4,
      subFields: [
        {
          name: 'country_code',
          label: 'Country Code',
          type: 'select',
          options: ['+39', '+1', '+44', '+49', '+33', '+34'],
          required: false,
        },
        {
          name: 'number',
          label: 'Phone Number',
          type: 'text',
          required: false,
          placeholder: 'e.g., 3201234567',
        },
      ],
    },
    {
      name: 'gender',
      label: 'Gender',
      type: 'select',
      options: ['Male', 'Female', 'Other', 'Prefer not to say'],
      required: false,
      order: 5,
    },
    {
      name: 'nationality',
      label: 'Nationality',
      type: 'select',
      options: ['Italy', 'EU Member', 'Other'],
      required: true,
      order: 6,
    },
    {
      name: 'date_of_birth',
      label: 'Date of Birth',
      type: 'date',
      required: false,
      order: 7,
    },
    {
      name: 'place_of_birth',
      label: 'Place of Birth',
      type: 'group',
      required: false,
      order: 8,
      subFields: [
        {
          name: 'country_selection',
          label: 'Country',
          type: 'select',
          options: ['Italy', 'EU Member', 'World'],
          required: false,
        },
      ],
    },
    {
      name: 'current_residence',
      label: 'Current Residence',
      type: 'group',
      required: true,
      order: 9,
      subFields: [
        {
          name: 'country',
          label: 'Country',
          type: 'select',
          options: ['Italy', 'EU Member', 'Other'],
          required: true,
        },
        {
          name: 'province',
          label: 'Province',
          type: 'text',
          required: false,
        },
        {
          name: 'city',
          label: 'City',
          type: 'text',
          required: false,
        },
        {
          name: 'address',
          label: 'Street Address',
          type: 'text',
          required: false,
        },
        {
          name: 'house_number',
          label: 'House Number',
          type: 'text',
          required: false,
        },
        {
          name: 'postal_code',
          label: 'Postal Code',
          type: 'text',
          required: false,
          maxLength: 5,
        },
      ],
    },
  ],
};

export const FORM_SCHEMAS = {
  // 1. ISEE Services
  ISEE_ORD_2026: {
    title: 'ISEE Ordinario 2026',
    description: 'Indicatore della Situazione Economica Equivalente - Ordinary Income Indicator Form 2026',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'family_information',
        title: 'Informazioni Familiari',
        fields: [
          {
            name: 'family_members',
            label: 'Family Members',
            type: 'dynamic_list',
            required: true,
            order: 1,
            subFields: [
              { name: 'name', label: 'Name', type: 'text', required: true },
              { name: 'tax_code', label: 'Tax Code', type: 'text', required: true },
              { name: 'relationship', label: 'Relationship', type: 'select', options: ['Spouse', 'Child', 'Parent', 'Sibling', 'Other'], required: true },
              { name: 'date_of_birth', label: 'Date of Birth', type: 'date', required: true },
            ],
          },
          {
            name: 'marital_status',
            label: 'Marital Status',
            type: 'select',
            options: ['Single', 'Married', 'Divorced', 'Widowed'],
            required: true,
            order: 2,
          },
          {
            name: 'number_of_dependents',
            label: 'Number of Dependents',
            type: 'number',
            required: false,
            order: 3,
          },
        ],
      },
      {
        id: 'asset_information',
        title: 'Informazioni su Beni Immobili',
        fields: [
          {
            name: 'real_estate_properties',
            label: 'Real Estate Properties',
            type: 'dynamic_list',
            required: false,
            order: 1,
            subFields: [
              { name: 'property_type', label: 'Type', type: 'select', options: ['House', 'Apartment', 'Land', 'Commercial'], required: true },
              { name: 'property_value', label: 'Estimated Value (€)', type: 'number', required: true },
              { name: 'ownership_percentage', label: 'Ownership %', type: 'number', required: true },
              { name: 'mortgaged', label: 'Mortgaged', type: 'checkbox', required: false },
              { name: 'mortgage_capital', label: 'Mortgage Capital (€)', type: 'number', required: false },
            ],
          },
          {
            name: 'liquid_assets',
            label: 'Liquid Assets (Bank, Savings)',
            type: 'number',
            required: false,
            order: 2,
            placeholder: '€',
          },
          {
            name: 'securities_stocks',
            label: 'Securities & Stocks',
            type: 'number',
            required: false,
            order: 3,
            placeholder: '€',
          },
          {
            name: 'bank_accounts',
            label: 'Bank Accounts',
            type: 'dynamic_list',
            required: false,
            order: 4,
            subFields: [
              { name: 'bank_name', label: 'Bank Name', type: 'text', required: true },
              { name: 'account_type', label: 'Account Type', type: 'select', options: ['Current', 'Savings', 'Investment'], required: true },
              { name: 'balance', label: 'Balance (€)', type: 'number', required: true },
              { name: 'average_balance', label: 'Average Balance (€)', type: 'number', required: false },
            ],
          },
        ],
      },
      {
        id: 'housing_information',
        title: 'Informazioni Abitazione',
        fields: [
          {
            name: 'housing_type',
            label: 'Housing Type',
            type: 'select',
            options: ['Owner-occupied', 'Rented', 'Provided by employer', 'Other'],
            required: true,
            order: 1,
          },
          {
            name: 'rent_amount',
            label: 'Monthly Rent (€)',
            type: 'number',
            required: false,
            order: 2,
            dependsOn: { field: 'housing_type', value: 'Rented' },
          },
          {
            name: 'mortgage_amount',
            label: 'Monthly Mortgage (€)',
            type: 'number',
            required: false,
            order: 3,
            dependsOn: { field: 'housing_type', value: 'Owner-occupied' },
          },
          {
            name: 'property_ownership_date',
            label: 'Date of Property Ownership',
            type: 'date',
            required: false,
            order: 4,
            dependsOn: { field: 'housing_type', value: 'Owner-occupied' },
          },
        ],
      },
      {
        id: 'vehicle_information',
        title: 'Informazioni Veicoli',
        fields: [
          {
            name: 'vehicles',
            label: 'Vehicles',
            type: 'dynamic_list',
            required: false,
            order: 1,
            subFields: [
              { name: 'vehicle_type', label: 'Type', type: 'select', options: ['Car', 'Motorcycle', 'Truck', 'Van', 'Other'], required: true },
              { name: 'vehicle_value', label: 'Value (€)', type: 'number', required: true },
              { name: 'purchase_year', label: 'Purchase Year', type: 'number', required: true },
              { name: 'registration_number', label: 'Registration Number', type: 'text', required: false },
            ],
          },
        ],
      },
      {
        id: 'income_information',
        title: 'Informazioni Reddito',
        fields: [
          {
            name: 'employment_status',
            label: 'Employment Status',
            type: 'select',
            options: ['Employed', 'Self-employed', 'Unemployed', 'Student', 'Retired', 'Disabled', 'Other'],
            required: true,
            order: 1,
          },
          {
            name: 'annual_income',
            label: 'Annual Income (€)',
            type: 'number',
            required: true,
            order: 2,
            dependsOn: { field: 'employment_status', value: 'Employed' },
          },
          {
            name: 'business_income',
            label: 'Business Income (€)',
            type: 'number',
            required: false,
            order: 3,
            dependsOn: { field: 'employment_status', value: 'Self-employed' },
          },
          {
            name: 'pension_income',
            label: 'Pension Income (€)',
            type: 'number',
            required: false,
            order: 4,
            dependsOn: { field: 'employment_status', value: 'Retired' },
          },
          {
            name: 'unemployment_benefits',
            label: 'Unemployment Benefits (€)',
            type: 'number',
            required: false,
            order: 5,
            dependsOn: { field: 'employment_status', value: 'Unemployed' },
          },
          {
            name: 'other_income',
            label: 'Other Income (€)',
            type: 'number',
            required: false,
            order: 6,
          },
          {
            name: 'income_tax_return',
            label: 'Income Tax Return (last 2 years)',
            type: 'file',
            required: true,
            order: 7,
          },
        ],
      },
      {
        id: 'disability_information',
        title: 'Informazioni Disabilità',
        fields: [
          {
            name: 'has_disability',
            label: 'Has Disability',
            type: 'checkbox',
            required: false,
            order: 1,
          },
          {
            name: 'disability_percentage',
            label: 'Disability Percentage (%)',
            type: 'number',
            required: false,
            order: 2,
            dependsOn: { field: 'has_disability', value: true },
          },
          {
            name: 'disability_certificate',
            label: 'Disability Certificate',
            type: 'file',
            required: false,
            order: 3,
            dependsOn: { field: 'has_disability', value: true },
          },
        ],
      },
    ],
  },

  ISEE_UNI_2026: {
    title: 'ISEE Universitario 2026',
    description: 'ISEE Form for University Students 2026',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'student_information',
        title: 'Informazioni Studente',
        fields: [
          {
            name: 'university_name',
            label: 'University Name',
            type: 'text',
            required: true,
            order: 1,
          },
          {
            name: 'degree_course',
            label: 'Degree Course',
            type: 'text',
            required: true,
            order: 2,
          },
          {
            name: 'enrollment_year',
            label: 'Enrollment Year',
            type: 'select',
            options: ['1st', '2nd', '3rd', '4th', '5th', '6th+'],
            required: true,
            order: 3,
          },
          {
            name: 'student_id',
            label: 'Student ID Number',
            type: 'text',
            required: true,
            order: 4,
          },
          {
            name: 'study_abroad',
            label: 'Studying Abroad',
            type: 'checkbox',
            required: false,
            order: 5,
          },
          {
            name: 'country_of_study',
            label: 'Country of Study',
            type: 'text',
            required: false,
            order: 6,
            dependsOn: { field: 'study_abroad', value: true },
          },
        ],
      },
      {
        id: 'family_information',
        title: 'Informazioni Familiari',
        fields: [
          {
            name: 'family_members',
            label: 'Family Members',
            type: 'dynamic_list',
            required: true,
            order: 1,
            subFields: [
              { name: 'name', label: 'Name', type: 'text', required: true },
              { name: 'tax_code', label: 'Tax Code', type: 'text', required: true },
              { name: 'relationship', label: 'Relationship', type: 'select', options: ['Parent', 'Sibling', 'Spouse', 'Other'], required: true },
            ],
          },
          {
            name: 'financially_independent',
            label: 'Financially Independent',
            type: 'checkbox',
            required: false,
            order: 2,
          },
        ],
      },
      {
        id: 'documents_information',
        title: 'Documenti Richiesti',
        fields: [
          {
            name: 'university_enrollment_certificate',
            label: 'University Enrollment Certificate',
            type: 'file',
            required: true,
            order: 1,
          },
          {
            name: 'identity_document',
            label: 'Identity Document',
            type: 'file',
            required: true,
            order: 2,
          },
          {
            name: 'tax_code_document',
            label: 'Tax Code Document',
            type: 'file',
            required: true,
            order: 3,
          },
          {
            name: 'family_members_documents',
            label: 'Family Members Documents',
            type: 'file',
            required: true,
            order: 4,
          },
        ],
      },
    ],
  },

  ISEE_SOC_2026: {
    title: 'ISEE Sociosanitario 2026',
    description: 'ISEE Form for Socio-Sanitary Services 2026',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'beneficiary_information',
        title: 'Informazioni Beneficiario',
        fields: [
          {
            name: 'beneficiary_type',
            label: 'Beneficiary Type',
            type: 'select',
            options: ['Child', 'Adult', 'Elderly'],
            required: true,
            order: 1,
          },
          {
            name: 'health_condition',
            label: 'Health Condition',
            type: 'text',
            required: true,
            order: 2,
          },
          {
            name: 'medical_certificate',
            label: 'Medical Certificate',
            type: 'file',
            required: true,
            order: 3,
          },
          {
            name: 'disability_status',
            label: 'Disability Status',
            type: 'select',
            options: ['No disability', 'Mild', 'Moderate', 'Severe'],
            required: true,
            order: 4,
          },
        ],
      },
      {
        id: 'family_unit_information',
        title: 'Composizione Nucleo Familiare',
        fields: [
          {
            name: 'family_members',
            label: 'Family Members',
            type: 'dynamic_list',
            required: true,
            order: 1,
            subFields: [
              { name: 'name', label: 'Name', type: 'text', required: true },
              { name: 'tax_code', label: 'Tax Code', type: 'text', required: true },
              { name: 'relationship', label: 'Relationship', type: 'select', options: ['Parent', 'Sibling', 'Spouse', 'Child', 'Caregiver', 'Other'], required: true },
            ],
          },
          {
            name: 'primary_caregiver',
            label: 'Primary Caregiver',
            type: 'text',
            required: false,
            order: 2,
          },
        ],
      },
      {
        id: 'financial_information',
        title: 'Informazioni Finanziarie',
        fields: [
          {
            name: 'annual_income',
            label: 'Annual Income (€)',
            type: 'number',
            required: true,
            order: 1,
          },
          {
            name: 'assets',
            label: 'Total Assets (€)',
            type: 'number',
            required: false,
            order: 2,
          },
          {
            name: 'healthcare_expenses',
            label: 'Healthcare Expenses (€/year)',
            type: 'number',
            required: false,
            order: 3,
          },
          {
            name: 'financial_documents',
            label: 'Financial Documents',
            type: 'file',
            required: true,
            order: 4,
          },
        ],
      },
    ],
  },

  ISEE_MIN_2026: {
    title: 'ISEE Minorile 2026',
    description: 'ISEE Form for Minor Children 2026',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'child_information',
        title: 'Informazioni Figlio Minore',
        fields: [
          {
            name: 'child_full_name',
            label: 'Child Full Name',
            type: 'text',
            required: true,
            order: 1,
          },
          {
            name: 'child_tax_code',
            label: 'Child Tax Code',
            type: 'text',
            required: true,
            order: 2,
            maxLength: 16,
          },
          {
            name: 'child_date_of_birth',
            label: 'Child Date of Birth',
            type: 'date',
            required: true,
            order: 3,
          },
          {
            name: 'legal_custody',
            label: 'Legal Custody',
            type: 'select',
            options: ['Both Parents', 'Mother Only', 'Father Only', 'Other'],
            required: true,
            order: 4,
          },
          {
            name: 'custody_documents',
            label: 'Custody Documents',
            type: 'file',
            required: false,
            order: 5,
            dependsOn: { field: 'legal_custody', value: 'Other' },
          },
        ],
      },
      {
        id: 'parents_information',
        title: 'Informazioni Genitori',
        fields: [
          {
            name: 'parent1_name',
            label: 'Parent 1 Name',
            type: 'text',
            required: true,
            order: 1,
          },
          {
            name: 'parent1_tax_code',
            label: 'Parent 1 Tax Code',
            type: 'text',
            required: true,
            order: 2,
            maxLength: 16,
          },
          {
            name: 'parent2_name',
            label: 'Parent 2 Name',
            type: 'text',
            required: false,
            order: 3,
          },
          {
            name: 'parent2_tax_code',
            label: 'Parent 2 Tax Code',
            type: 'text',
            required: false,
            order: 4,
            maxLength: 16,
          },
          {
            name: 'marital_status',
            label: 'Parents Marital Status',
            type: 'select',
            options: ['Married', 'Separated', 'Divorced', 'Single Parent'],
            required: true,
            order: 5,
          },
          {
            name: 'combined_income',
            label: 'Combined Annual Income (€)',
            type: 'number',
            required: true,
            order: 6,
          },
        ],
      },
    ],
  },

  ISEE_COR_2026: {
    title: 'ISEE Corrispettivo 2026',
    description: 'Corrective ISEE Form 2026',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'change_of_circumstances',
        title: 'Cambio Circostanze',
        fields: [
          {
            name: 'reason_for_change',
            label: 'Reason for Application',
            type: 'select',
            options: ['Employment change', 'Income change', 'Family structure change', 'Property sale/purchase', 'Separation/Divorce', 'Other'],
            required: true,
            order: 1,
          },
          {
            name: 'change_date',
            label: 'Date of Change',
            type: 'date',
            required: true,
            order: 2,
          },
          {
            name: 'change_description',
            label: 'Description of Change',
            type: 'textarea',
            required: true,
            order: 3,
          },
          {
            name: 'supporting_documents',
            label: 'Supporting Documents',
            type: 'file',
            required: true,
            order: 4,
          },
        ],
      },
      {
        id: 'employment_information',
        title: 'Informazioni Occupazionali',
        fields: [
          {
            name: 'employment_status',
            label: 'Employment Status',
            type: 'select',
            options: ['Employed', 'Self-employed', 'Unemployed', 'Retired'],
            required: true,
            order: 1,
          },
          {
            name: 'employer_name',
            label: 'Employer Name',
            type: 'text',
            required: false,
            order: 2,
            dependsOn: { field: 'employment_status', value: 'Employed' },
          },
          {
            name: 'new_salary',
            label: 'New Salary (€)',
            type: 'number',
            required: false,
            order: 3,
            dependsOn: { field: 'employment_status', value: 'Employed' },
          },
          {
            name: 'income_certificate',
            label: 'Income Certificate',
            type: 'file',
            required: true,
            order: 4,
          },
        ],
      },
      {
        id: 'asset_information',
        title: 'Informazioni Patrimoniali Aggiornate',
        fields: [
          {
            name: 'current_assets',
            label: 'Current Total Assets (€)',
            type: 'number',
            required: false,
            order: 1,
          },
          {
            name: 'asset_transfer',
            label: 'Asset Transfer or Sale',
            type: 'checkbox',
            required: false,
            order: 2,
          },
          {
            name: 'asset_details',
            label: 'Asset Details',
            type: 'textarea',
            required: false,
            order: 3,
            dependsOn: { field: 'asset_transfer', value: true },
          },
          {
            name: 'asset_documents',
            label: 'Asset Documents',
            type: 'file',
            required: false,
            order: 4,
            dependsOn: { field: 'asset_transfer', value: true },
          },
        ],
      },
    ],
  },

  // 2. Unemployment Benefits Services
  NASP_2026: {
    title: 'NASPI 2026',
    description: 'Application for New Social Safety Net (Nuova Assicurazione Sociale per l\'Disoccupazione)',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'applicant_information',
        title: 'Informazioni Candidato',
        fields: [
          {
            name: 'tax_code',
            label: 'Tax Code (Codice Fiscale)',
            type: 'text',
            required: true,
            order: 1,
            maxLength: 16,
          },
          {
            name: 'place_of_birth',
            label: 'Place of Birth',
            type: 'text',
            required: true,
            order: 2,
          },
          {
            name: 'marital_status',
            label: 'Marital Status',
            type: 'select',
            options: ['Single', 'Married', 'Divorced', 'Widowed'],
            required: true,
            order: 3,
          },
          {
            name: 'number_of_dependents',
            label: 'Number of Dependents',
            type: 'number',
            required: false,
            order: 4,
          },
        ],
      },
      {
        id: 'employment_history',
        title: 'Cronologia Occupazionale',
        fields: [
          {
            name: 'last_employer',
            label: 'Last Employer Name',
            type: 'text',
            required: true,
            order: 1,
          },
          {
            name: 'employment_start_date',
            label: 'Employment Start Date',
            type: 'date',
            required: true,
            order: 2,
          },
          {
            name: 'employment_end_date',
            label: 'Employment End Date (Termination)',
            type: 'date',
            required: true,
            order: 3,
          },
          {
            name: 'reason_for_dismissal',
            label: 'Reason for Dismissal',
            type: 'select',
            options: ['Redundancy', 'Layoff', 'Contract expiration', 'Mutual agreement', 'Just cause', 'Other'],
            required: true,
            order: 4,
          },
          {
            name: 'severance_pay_received',
            label: 'Severance Pay Received (€)',
            type: 'number',
            required: false,
            order: 5,
          },
          {
            name: 'employment_contract_copy',
            label: 'Employment Contract Copy',
            type: 'file',
            required: true,
            order: 6,
          },
          {
            name: 'termination_letter',
            label: 'Termination Letter',
            type: 'file',
            required: true,
            order: 7,
          },
        ],
      },
      {
        id: 'documents_and_bank',
        title: 'Documenti e Dati Bancari',
        fields: [
          {
            name: 'identity_document',
            label: 'Identity Document',
            type: 'file',
            required: true,
            order: 1,
          },
          {
            name: 'bank_account_details',
            label: 'Bank Account Details',
            type: 'group',
            required: true,
            order: 2,
            subFields: [
              {
                name: 'bank_name',
                label: 'Bank Name',
                type: 'text',
                required: true,
              },
              {
                name: 'iban',
                label: 'IBAN',
                type: 'text',
                required: true,
              },
              {
                name: 'account_holder',
                label: 'Account Holder Name',
                type: 'text',
                required: true,
              },
            ],
          },
          {
            name: 'bank_statement',
            label: 'Recent Bank Statement',
            type: 'file',
            required: true,
            order: 3,
          },
        ],
      },
    ],
  },

  DAGRN_2026: {
    title: 'Disoccupazione Agricola 2026',
    description: 'Agricultural Unemployment Benefit Application 2026',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'applicant_information',
        title: 'Informazioni Candidato',
        fields: [
          {
            name: 'tax_code',
            label: 'Tax Code (Codice Fiscale)',
            type: 'text',
            required: true,
            order: 1,
            maxLength: 16,
          },
          {
            name: 'agricultural_worker_type',
            label: 'Agricultural Worker Type',
            type: 'select',
            options: ['Seasonal', 'Permanent', 'Casual'],
            required: true,
            order: 2,
          },
          {
            name: 'years_of_experience',
            label: 'Years of Agricultural Experience',
            type: 'number',
            required: true,
            order: 3,
          },
        ],
      },
      {
        id: 'agricultural_employment',
        title: 'Storico Lavoro Agricolo',
        fields: [
          {
            name: 'last_employer',
            label: 'Last Employer (Farm/Agricultural Entity)',
            type: 'text',
            required: true,
            order: 1,
          },
          {
            name: 'employment_period',
            label: 'Employment Period',
            type: 'group',
            required: true,
            order: 2,
            subFields: [
              {
                name: 'start_date',
                label: 'Start Date',
                type: 'date',
                required: true,
              },
              {
                name: 'end_date',
                label: 'End Date',
                type: 'date',
                required: true,
              },
            ],
          },
          {
            name: 'hours_worked',
            label: 'Total Hours Worked',
            type: 'number',
            required: true,
            order: 3,
          },
          {
            name: 'agriculture_employment_certificate',
            label: 'Agricultural Employment Certificate',
            type: 'file',
            required: true,
            order: 4,
          },
        ],
      },
      {
        id: 'documents_and_bank',
        title: 'Documenti e Dati Bancari',
        fields: [
          {
            name: 'identity_document',
            label: 'Identity Document',
            type: 'file',
            required: true,
            order: 1,
          },
          {
            name: 'bank_account',
            label: 'Bank Account',
            type: 'group',
            required: true,
            order: 2,
            subFields: [
              {
                name: 'bank_name',
                label: 'Bank Name',
                type: 'text',
                required: true,
              },
              {
                name: 'iban',
                label: 'IBAN',
                type: 'text',
                required: true,
              },
            ],
          },
          {
            name: 'contribution_statement',
            label: 'Contribution Statement',
            type: 'file',
            required: true,
            order: 3,
          },
        ],
      },
    ],
  },

  ANTNAS_2026: {
    title: 'Anticipo NASPI 2026',
    description: 'NASPI Unemployment Benefit Advance Request 2026',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'applicant_information',
        title: 'Informazioni Candidato',
        fields: [
          {
            name: 'tax_code',
            label: 'Tax Code (Codice Fiscale)',
            type: 'text',
            required: true,
            order: 1,
            maxLength: 16,
          },
          {
            name: 'naspi_application_date',
            label: 'NASPI Application Date',
            type: 'date',
            required: true,
            order: 2,
          },
          {
            name: 'naspi_reference_number',
            label: 'NASPI Reference Number',
            type: 'text',
            required: false,
            order: 3,
          },
        ],
      },
      {
        id: 'naspi_information',
        title: 'Informazioni NASPI',
        fields: [
          {
            name: 'monthly_benefit_amount',
            label: 'Expected Monthly Benefit Amount (€)',
            type: 'number',
            required: true,
            order: 1,
          },
          {
            name: 'advance_requested',
            label: 'Advance Amount Requested (€)',
            type: 'number',
            required: true,
            order: 2,
          },
          {
            name: 'advance_justification',
            label: 'Justification for Advance',
            type: 'textarea',
            required: true,
            order: 3,
          },
          {
            name: 'naspi_decision_letter',
            label: 'NASPI Decision Letter',
            type: 'file',
            required: true,
            order: 4,
          },
          {
            name: 'bank_account',
            label: 'Bank Account for Direct Deposit',
            type: 'group',
            required: true,
            order: 5,
            subFields: [
              {
                name: 'bank_name',
                label: 'Bank Name',
                type: 'text',
                required: true,
              },
              {
                name: 'iban',
                label: 'IBAN',
                type: 'text',
                required: true,
              },
            ],
          },
        ],
      },
    ],
  },

  DID_2026: {
    title: 'Disoccupazione con Diritto 2026',
    description: 'Unemployment with Rights Protection Program 2026',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'applicant_information',
        title: 'Informazioni Candidato',
        fields: [
          {
            name: 'tax_code',
            label: 'Tax Code (Codice Fiscale)',
            type: 'text',
            required: true,
            order: 1,
            maxLength: 16,
          },
          {
            name: 'age',
            label: 'Age',
            type: 'number',
            required: true,
            order: 2,
          },
          {
            name: 'employment_duration',
            label: 'Years of Employment History',
            type: 'number',
            required: true,
            order: 3,
          },
        ],
      },
      {
        id: 'job_search_plan',
        title: 'Piano Ricerca Lavoro',
        fields: [
          {
            name: 'job_search_activities',
            label: 'Job Search Activities',
            type: 'dynamic_list',
            required: true,
            order: 1,
            subFields: [
              {
                name: 'activity_type',
                label: 'Activity Type',
                type: 'select',
                options: ['Job applications', 'Training courses', 'Interviews', 'Networking', 'Other'],
                required: true,
              },
              {
                name: 'frequency',
                label: 'Frequency',
                type: 'select',
                options: ['Weekly', 'Bi-weekly', 'Monthly'],
                required: true,
              },
              {
                name: 'description',
                label: 'Description',
                type: 'textarea',
                required: false,
              },
            ],
          },
          {
            name: 'willing_to_relocate',
            label: 'Willing to Relocate',
            type: 'checkbox',
            required: false,
            order: 2,
          },
          {
            name: 'desired_job_sector',
            label: 'Desired Job Sector',
            type: 'select',
            options: ['Technology', 'Healthcare', 'Manufacturing', 'Services', 'Education', 'Other'],
            required: true,
            order: 3,
          },
          {
            name: 'special_skills',
            label: 'Special Skills or Certifications',
            type: 'textarea',
            required: false,
            order: 4,
          },
          {
            name: 'skills_certifications',
            label: 'Skills/Certifications Documents',
            type: 'file',
            required: false,
            order: 5,
          },
        ],
      },
    ],
  },
};
