// Form schemas for all services based on DATA.md requirements
// Every service includes comprehensive personal information section

const PERSONAL_INFORMATION_SECTION = {
  id: 'personal_information',
  title: 'Informazioni Personali',
  description: 'Informazioni personali e di contatto del dichiarante',
  fields: [
    {
      name: 'name',
      label: 'Nome',
      type: 'text',
      required: true,
      order: 1,
      maxLength: 100,
    },
    {
      name: 'surname',
      label: 'Cognome',
      type: 'text',
      required: true,
      order: 2,
      maxLength: 100,
    },
    {
      name: 'email',
      label: 'Email',
      type: 'email',
      required: true,
      order: 3,
    },
    {
      name: 'mobile_phone_number',
      label: 'Numero di telefono cellulare',
      type: 'group',
      required: false,
      order: 4,
      subFields: [
        {
          name: 'country_code',
          label: 'Prefisso',
          type: 'select',
          options: ['+39', '+1', '+44', '+49', '+33', '+34'],
          required: false,
        },
        {
          name: 'number',
          label: 'Numero di telefono',
          type: 'text',
          required: false,
          placeholder: 'es. 3201234567',
        },
      ],
    },
    {
      name: 'gender',
      label: 'Sesso',
      type: 'select',
      options: ['Maschio', 'Femmina', 'Altro', 'Preferisco non specificare'],
      required: false,
      order: 5,
    },
    {
      name: 'nationality',
      label: 'Nazionalità',
      type: 'select',
      options: ['Italia', 'Unione Europea', 'Altro'],
      required: true,
      order: 6,
    },
    {
      name: 'date_of_birth',
      label: 'Data di nascita',
      type: 'date',
      required: false,
      order: 7,
    },
    {
      name: 'place_of_birth',
      label: 'Luogo di nascita',
      type: 'group',
      required: false,
      order: 8,
      subFields: [
        {
          name: 'country_selection',
          label: 'Paese',
          type: 'select',
          options: ['Italia', 'Unione Europea', 'Altro'],
          required: false,
        },
      ],
    },
    {
      name: 'current_residence',
      label: 'Residenza attuale',
      type: 'group',
      required: true,
      order: 9,
      subFields: [
        {
          name: 'country',
          label: 'Paese',
          type: 'select',
          options: ['Italia', 'Unione Europea', 'Altro'],
          required: true,
        },
        {
          name: 'province',
          label: 'Provincia',
          type: 'text',
          required: false,
        },
        {
          name: 'city',
          label: 'Città',
          type: 'text',
          required: false,
        },
        {
          name: 'address',
          label: 'Indirizzo',
          type: 'text',
          required: false,
        },
        {
          name: 'house_number',
          label: 'Numero civico',
          type: 'text',
          required: false,
        },
        {
          name: 'postal_code',
          label: 'CAP',
          type: 'text',
          required: false,
          maxLength: 5,
        },
      ],
    },
    {
      name: 'permesso_soggiorno',
      label: 'Permesso di soggiorno (se extracomunitario)',
      type: 'file',
      required: false,
      order: 10,
      description: 'Allega permesso di soggiorno',
    },
    {
      name: 'permesso_expiry_date',
      label: 'Data di scadenza permesso',
      type: 'date',
      required: false,
      order: 11,
      description: 'Se scaduto, devi anche caricare la ricevuta',
    },
    {
      name: 'permesso_ricevuta',
      label: 'Ricevuta (se permesso scaduto)',
      type: 'file',
      required: false,
      order: 12,
      description: 'Allega ricevuta se il permesso è scaduto',
    },
    {
      name: 'stato_civile',
      label: 'Stato civile',
      type: 'select',
      options: ['Celibe / Nubile', 'Coniugato/a', 'Separato/a', 'Divorziato/a', 'Vedovo/a'],
      required: true,
      order: 13,
    },
  ],
};

// Declarations and Authorization Section - MUST be last section in all services
const DECLARATIONS_AUTHORIZATION_SECTION = {
  id: 'declarations_authorization',
  title: 'Dichiarazioni e Autorizzazioni',
  description: 'Consensi richiesti e firma digitale',
  fields: [
    {
      name: 'declare_data_truthful',
      label: 'Dichiaro che i dati forniti sono veritieri',
      type: 'checkbox',
      required: true,
      order: 1,
    },
    {
      name: 'authorize_gdpr',
      label: 'Autorizzo il trattamento dei dati personali (GDPR)',
      type: 'checkbox',
      required: true,
      order: 2,
    },
    {
      name: 'delegate_caf_dsu',
      label: 'Delega CAF per invio DSU',
      type: 'checkbox',
      required: true,
      order: 3,
    },
    {
      name: 'recontact_other_services',
      label: 'Desidero essere ricontattato per altri servizi CAF / Patronato',
      type: 'checkbox',
      required: false,
      order: 4,
    },
    {
      name: 'digital_signature',
      label: 'Firma Digitale',
      type: 'signature',
      required: true,
      order: 5,
      description: 'Inserisci la tua firma digitale',
    },
    {
      name: 'full_name_signature',
      label: 'Nome e Cognome',
      type: 'text',
      required: true,
      order: 6,
      description: 'Nome completo per la verifica della firma',
    },
  ],
};

// Export reusable sections
export { PERSONAL_INFORMATION_SECTION };
export { DECLARATIONS_AUTHORIZATION_SECTION };

export const FORM_SCHEMAS = {
  // 1. ISEE Services
  ISEE_ORD_2026: {
    title: 'ISEE Ordinario 2026',
    description: 'Indicatore della Situazione Economica Equivalente - Modulo Ordinario 2026',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'family_information',
        title: 'Informazioni Familiari',
        fields: [
          {
            name: 'family_members',
            label: 'Family Members',
            type: 'dynamic_list',
            required: true,
            order: 1,
            subFields: [
              { name: 'name', label: 'Name', type: 'text', required: true },
              { name: 'tax_code', label: 'Tax Code', type: 'text', required: true },
              { name: 'relationship', label: 'Relationship', type: 'select', options: ['Spouse', 'Child', 'Parent', 'Sibling', 'Other'], required: true },
              { name: 'date_of_birth', label: 'Date of Birth', type: 'date', required: true },
            ],
          },
          {
            name: 'marital_status',
            label: 'Marital Status',
            type: 'select',
            options: ['Single', 'Married', 'Divorced', 'Widowed'],
            required: true,
            order: 2,
          },
          {
            name: 'number_of_dependents',
            label: 'Number of Dependents',
            type: 'number',
            required: false,
            order: 3,
          },
        ],
      },
      {
        id: 'asset_information',
        title: 'Informazioni su Beni Immobili',
        fields: [
          {
            name: 'real_estate_properties',
            label: 'Real Estate Properties',
            type: 'dynamic_list',
            required: false,
            order: 1,
            subFields: [
              { name: 'property_type', label: 'Type', type: 'select', options: ['House', 'Apartment', 'Land', 'Commercial'], required: true },
              { name: 'property_value', label: 'Estimated Value (€)', type: 'number', required: true },
              { name: 'ownership_percentage', label: 'Ownership %', type: 'number', required: true },
              { name: 'mortgaged', label: 'Mortgaged', type: 'checkbox', required: false },
              { name: 'mortgage_capital', label: 'Mortgage Capital (€)', type: 'number', required: false },
            ],
          },
          {
            name: 'liquid_assets',
            label: 'Liquid Assets (Bank, Savings)',
            type: 'number',
            required: false,
            order: 2,
            placeholder: '€',
          },
          {
            name: 'securities_stocks',
            label: 'Securities & Stocks',
            type: 'number',
            required: false,
            order: 3,
            placeholder: '€',
          },
          {
            name: 'bank_accounts',
            label: 'Bank Accounts',
            type: 'dynamic_list',
            required: false,
            order: 4,
            subFields: [
              { name: 'bank_name', label: 'Bank Name', type: 'text', required: true },
              { name: 'account_type', label: 'Account Type', type: 'select', options: ['Current', 'Savings', 'Investment'], required: true },
              { name: 'balance', label: 'Balance (€)', type: 'number', required: true },
              { name: 'average_balance', label: 'Average Balance (€)', type: 'number', required: false },
            ],
          },
        ],
      },
      {
        id: 'housing_information',
        title: 'Informazioni Abitazione',
        fields: [
          {
            name: 'housing_type',
            label: 'Housing Type',
            type: 'select',
            options: ['Owner-occupied', 'Rented', 'Provided by employer', 'Other'],
            required: true,
            order: 1,
          },
          {
            name: 'rent_amount',
            label: 'Monthly Rent (€)',
            type: 'number',
            required: false,
            order: 2,
            dependsOn: { field: 'housing_type', value: 'Rented' },
          },
          {
            name: 'mortgage_amount',
            label: 'Monthly Mortgage (€)',
            type: 'number',
            required: false,
            order: 3,
            dependsOn: { field: 'housing_type', value: 'Owner-occupied' },
          },
          {
            name: 'property_ownership_date',
            label: 'Date of Property Ownership',
            type: 'date',
            required: false,
            order: 4,
            dependsOn: { field: 'housing_type', value: 'Owner-occupied' },
          },
        ],
      },
      {
        id: 'vehicle_information',
        title: 'Informazioni Veicoli',
        fields: [
          {
            name: 'vehicles',
            label: 'Vehicles',
            type: 'dynamic_list',
            required: false,
            order: 1,
            subFields: [
              { name: 'vehicle_type', label: 'Type', type: 'select', options: ['Car', 'Motorcycle', 'Truck', 'Van', 'Other'], required: true },
              { name: 'vehicle_value', label: 'Value (€)', type: 'number', required: true },
              { name: 'purchase_year', label: 'Purchase Year', type: 'number', required: true },
              { name: 'registration_number', label: 'Registration Number', type: 'text', required: false },
            ],
          },
        ],
      },
      {
        id: 'income_information',
        title: 'Informazioni Reddito',
        fields: [
          {
            name: 'employment_status',
            label: 'Employment Status',
            type: 'select',
            options: ['Employed', 'Self-employed', 'Unemployed', 'Student', 'Retired', 'Disabled', 'Other'],
            required: true,
            order: 1,
          },
          {
            name: 'annual_income',
            label: 'Annual Income (€)',
            type: 'number',
            required: true,
            order: 2,
            dependsOn: { field: 'employment_status', value: 'Employed' },
          },
          {
            name: 'business_income',
            label: 'Business Income (€)',
            type: 'number',
            required: false,
            order: 3,
            dependsOn: { field: 'employment_status', value: 'Self-employed' },
          },
          {
            name: 'pension_income',
            label: 'Pension Income (€)',
            type: 'number',
            required: false,
            order: 4,
            dependsOn: { field: 'employment_status', value: 'Retired' },
          },
          {
            name: 'unemployment_benefits',
            label: 'Unemployment Benefits (€)',
            type: 'number',
            required: false,
            order: 5,
            dependsOn: { field: 'employment_status', value: 'Unemployed' },
          },
          {
            name: 'other_income',
            label: 'Other Income (€)',
            type: 'number',
            required: false,
            order: 6,
          },
          {
            name: 'income_tax_return',
            label: 'Income Tax Return (last 2 years)',
            type: 'file',
            required: true,
            order: 7,
          },
        ],
      },
      {
        id: 'disability_information',
        title: 'Informazioni Disabilità',
        fields: [
          {
            name: 'has_disability',
            label: 'Has Disability',
            type: 'checkbox',
            required: false,
            order: 1,
          },
          {
            name: 'disability_percentage',
            label: 'Disability Percentage (%)',
            type: 'number',
            required: false,
            order: 2,
            dependsOn: { field: 'has_disability', value: true },
          },
          {
            name: 'disability_certificate',
            label: 'Disability Certificate',
            type: 'file',
            required: false,
            order: 3,
            dependsOn: { field: 'has_disability', value: true },
          },
        ],
      },
      DECLARATIONS_AUTHORIZATION_SECTION,
    ],
  },

  ISEE_UNI_2026: {
    title: 'ISEE Universitario 2026',
    description: 'Modulo ISEE per Studenti Universitari 2026',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'student_information',
        title: 'Informazioni Studente',
        fields: [
          {
            name: 'university_name',
            label: 'University Name',
            type: 'text',
            required: true,
            order: 1,
          },
          {
            name: 'degree_course',
            label: 'Degree Course',
            type: 'text',
            required: true,
            order: 2,
          },
          {
            name: 'enrollment_year',
            label: 'Enrollment Year',
            type: 'select',
            options: ['1st', '2nd', '3rd', '4th', '5th', '6th+'],
            required: true,
            order: 3,
          },
          {
            name: 'student_id',
            label: 'Student ID Number',
            type: 'text',
            required: true,
            order: 4,
          },
          {
            name: 'study_abroad',
            label: 'Studying Abroad',
            type: 'checkbox',
            required: false,
            order: 5,
          },
          {
            name: 'country_of_study',
            label: 'Country of Study',
            type: 'text',
            required: false,
            order: 6,
            dependsOn: { field: 'study_abroad', value: true },
          },
        ],
      },
      {
        id: 'family_information',
        title: 'Informazioni Familiari',
        fields: [
          {
            name: 'family_members',
            label: 'Family Members',
            type: 'dynamic_list',
            required: true,
            order: 1,
            subFields: [
              { name: 'name', label: 'Name', type: 'text', required: true },
              { name: 'tax_code', label: 'Tax Code', type: 'text', required: true },
              { name: 'relationship', label: 'Relationship', type: 'select', options: ['Parent', 'Sibling', 'Spouse', 'Other'], required: true },
            ],
          },
          {
            name: 'financially_independent',
            label: 'Financially Independent',
            type: 'checkbox',
            required: false,
            order: 2,
          },
        ],
      },
      {
        id: 'documents_information',
        title: 'Documenti Richiesti',
        fields: [
          {
            name: 'university_enrollment_certificate',
            label: 'University Enrollment Certificate',
            type: 'file',
            required: true,
            order: 1,
          },
          {
            name: 'identity_document',
            label: 'Identity Document',
            type: 'file',
            required: true,
            order: 2,
          },
          {
            name: 'tax_code_document',
            label: 'Tax Code Document',
            type: 'file',
            required: true,
            order: 3,
          },
          {
            name: 'family_members_documents',
            label: 'Family Members Documents',
            type: 'file',
            required: true,
            order: 4,
          },
        ],
      },
      DECLARATIONS_AUTHORIZATION_SECTION,
    ],
  },

  ISEE_SOC_2026: {
    title: 'ISEE Sociosanitario 2026',
    description: 'Modulo ISEE per Servizi Socio-Sanitari 2026',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'beneficiary_information',
        title: 'Informazioni Beneficiario',
        fields: [
          {
            name: 'beneficiary_type',
            label: 'Beneficiary Type',
            type: 'select',
            options: ['Child', 'Adult', 'Elderly'],
            required: true,
            order: 1,
          },
          {
            name: 'health_condition',
            label: 'Health Condition',
            type: 'text',
            required: true,
            order: 2,
          },
          {
            name: 'medical_certificate',
            label: 'Medical Certificate',
            type: 'file',
            required: true,
            order: 3,
          },
          {
            name: 'disability_status',
            label: 'Disability Status',
            type: 'select',
            options: ['No disability', 'Mild', 'Moderate', 'Severe'],
            required: true,
            order: 4,
          },
        ],
      },
      {
        id: 'family_unit_information',
        title: 'Composizione Nucleo Familiare',
        fields: [
          {
            name: 'family_members',
            label: 'Family Members',
            type: 'dynamic_list',
            required: true,
            order: 1,
            subFields: [
              { name: 'name', label: 'Name', type: 'text', required: true },
              { name: 'tax_code', label: 'Tax Code', type: 'text', required: true },
              { name: 'relationship', label: 'Relationship', type: 'select', options: ['Parent', 'Sibling', 'Spouse', 'Child', 'Caregiver', 'Other'], required: true },
            ],
          },
          {
            name: 'primary_caregiver',
            label: 'Primary Caregiver',
            type: 'text',
            required: false,
            order: 2,
          },
        ],
      },
      {
        id: 'financial_information',
        title: 'Informazioni Finanziarie',
        fields: [
          {
            name: 'annual_income',
            label: 'Annual Income (€)',
            type: 'number',
            required: true,
            order: 1,
          },
          {
            name: 'assets',
            label: 'Total Assets (€)',
            type: 'number',
            required: false,
            order: 2,
          },
          {
            name: 'healthcare_expenses',
            label: 'Healthcare Expenses (€/year)',
            type: 'number',
            required: false,
            order: 3,
          },
          {
            name: 'financial_documents',
            label: 'Financial Documents',
            type: 'file',
            required: true,
            order: 4,
          },
        ],
      },
      DECLARATIONS_AUTHORIZATION_SECTION,
    ],
  },

  ISEE_MIN_2026: {
    title: 'ISEE Minorile 2026',
    description: 'Modulo ISEE per Minorenni 2026',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'child_information',
        title: 'Informazioni Figlio Minore',
        fields: [
          {
            name: 'child_full_name',
            label: 'Child Full Name',
            type: 'text',
            required: true,
            order: 1,
          },
          {
            name: 'child_tax_code',
            label: 'Child Tax Code',
            type: 'text',
            required: true,
            order: 2,
            maxLength: 16,
          },
          {
            name: 'child_date_of_birth',
            label: 'Child Date of Birth',
            type: 'date',
            required: true,
            order: 3,
          },
          {
            name: 'legal_custody',
            label: 'Legal Custody',
            type: 'select',
            options: ['Both Parents', 'Mother Only', 'Father Only', 'Other'],
            required: true,
            order: 4,
          },
          {
            name: 'custody_documents',
            label: 'Custody Documents',
            type: 'file',
            required: false,
            order: 5,
            dependsOn: { field: 'legal_custody', value: 'Other' },
          },
        ],
      },
      {
        id: 'parents_information',
        title: 'Informazioni Genitori',
        fields: [
          {
            name: 'parent1_name',
            label: 'Parent 1 Name',
            type: 'text',
            required: true,
            order: 1,
          },
          {
            name: 'parent1_tax_code',
            label: 'Parent 1 Tax Code',
            type: 'text',
            required: true,
            order: 2,
            maxLength: 16,
          },
          {
            name: 'parent2_name',
            label: 'Parent 2 Name',
            type: 'text',
            required: false,
            order: 3,
          },
          {
            name: 'parent2_tax_code',
            label: 'Parent 2 Tax Code',
            type: 'text',
            required: false,
            order: 4,
            maxLength: 16,
          },
          {
            name: 'marital_status',
            label: 'Parents Marital Status',
            type: 'select',
            options: ['Married', 'Separated', 'Divorced', 'Single Parent'],
            required: true,
            order: 5,
          },
          {
            name: 'combined_income',
            label: 'Combined Annual Income (€)',
            type: 'number',
            required: true,
            order: 6,
          },
        ],
      },
      DECLARATIONS_AUTHORIZATION_SECTION,
    ],
  },

  ISEE_COR_2026: {
    title: 'ISEE Corrispettivo 2026',
    description: 'Modulo ISEE Corrente 2026',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'change_of_circumstances',
        title: 'Cambio Circostanze',
        fields: [
          {
            name: 'reason_for_change',
            label: 'Reason for Application',
            type: 'select',
            options: ['Employment change', 'Income change', 'Family structure change', 'Property sale/purchase', 'Separation/Divorce', 'Other'],
            required: true,
            order: 1,
          },
          {
            name: 'change_date',
            label: 'Date of Change',
            type: 'date',
            required: true,
            order: 2,
          },
          {
            name: 'change_description',
            label: 'Description of Change',
            type: 'textarea',
            required: true,
            order: 3,
          },
          {
            name: 'supporting_documents',
            label: 'Supporting Documents',
            type: 'file',
            required: true,
            order: 4,
          },
        ],
      },
      {
        id: 'employment_information',
        title: 'Informazioni Occupazionali',
        fields: [
          {
            name: 'employment_status',
            label: 'Employment Status',
            type: 'select',
            options: ['Employed', 'Self-employed', 'Unemployed', 'Retired'],
            required: true,
            order: 1,
          },
          {
            name: 'employer_name',
            label: 'Employer Name',
            type: 'text',
            required: false,
            order: 2,
            dependsOn: { field: 'employment_status', value: 'Employed' },
          },
          {
            name: 'new_salary',
            label: 'New Salary (€)',
            type: 'number',
            required: false,
            order: 3,
            dependsOn: { field: 'employment_status', value: 'Employed' },
          },
          {
            name: 'income_certificate',
            label: 'Income Certificate',
            type: 'file',
            required: true,
            order: 4,
          },
        ],
      },
      {
        id: 'asset_information',
        title: 'Informazioni Patrimoniali Aggiornate',
        fields: [
          {
            name: 'current_assets',
            label: 'Current Total Assets (€)',
            type: 'number',
            required: false,
            order: 1,
          },
          {
            name: 'asset_transfer',
            label: 'Asset Transfer or Sale',
            type: 'checkbox',
            required: false,
            order: 2,
          },
          {
            name: 'asset_details',
            label: 'Asset Details',
            type: 'textarea',
            required: false,
            order: 3,
            dependsOn: { field: 'asset_transfer', value: true },
          },
          {
            name: 'asset_documents',
            label: 'Asset Documents',
            type: 'file',
            required: false,
            order: 4,
            dependsOn: { field: 'asset_transfer', value: true },
          },
        ],
      },
      DECLARATIONS_AUTHORIZATION_SECTION,
    ],
  },

  // 2. Unemployment Benefits Services - Disoccupazione / NASPI
  // Order: 1-NASPI, 2-Agricola, 3-Anticipo, 4-DID, 5-PAD, 6-NASPI-Com, 7-Ricorso
  NASP_2026: {
    title: 'Disoccupazione NASPI',
    description: 'Domanda di Disoccupazione NASpI (Nuova Assicurazione Sociale per l\'Impiego)',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'documenti_richiesti',
        title: 'Documenti Richiesti',
        description: 'Carica i documenti necessari per la domanda NASPI',
        fields: [
          {
            name: 'documento_riconoscimento',
            label: 'Documento di riconoscimento',
            type: 'file',
            required: true,
            order: 1,
            description: 'Carta d\'identità italiana, Carta d\'identità di un paese comunitario, Patente o Passaporto',
          },
          {
            name: 'codice_fiscale_tessera',
            label: 'Codice Fiscale o Tessera Sanitaria',
            type: 'file',
            required: true,
            order: 2,
            description: 'Fronte e retro',
          },
          {
            name: 'permesso_soggiorno',
            label: 'Permesso di soggiorno del richiedente',
            type: 'file',
            required: false,
            order: 3,
            description: 'Obbligatorio se extracomunitario',
          },
          {
            name: 'ultima_busta_paga',
            label: 'Ultima Busta Paga in possesso',
            type: 'file',
            required: true,
            order: 4,
            description: 'Allega l\'ultima busta paga',
          },
          {
            name: 'lettera_licenziamento',
            label: 'Lettera di licenziamento / Contratto scaduto',
            type: 'file',
            required: true,
            order: 5,
            description: 'Allega la lettera di licenziamento o il contratto scaduto',
          },
        ],
      },
      DECLARATIONS_AUTHORIZATION_SECTION,
    ],
  },

  DAGRN_2026: {
    title: 'Disoccupazione Agricola',
    description: 'Domanda di indennità di disoccupazione agricola',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'documenti_richiesti',
        title: 'Documenti Richiesti',
        description: 'Carica i documenti necessari per la domanda di disoccupazione agricola',
        fields: [
          {
            name: 'carta_identita',
            label: 'Carta d\'identità richiedente',
            type: 'file',
            required: true,
            order: 1,
            description: 'Fronte e retro',
          },
          {
            name: 'codice_fiscale_tessera',
            label: 'Codice Fiscale / Tessera Sanitaria del richiedente',
            type: 'file',
            required: true,
            order: 2,
            description: 'Fronte e retro',
          },
          {
            name: 'iban',
            label: 'IBAN richiedente',
            type: 'text',
            required: true,
            order: 3,
            description: 'Inserisci il tuo IBAN',
          },
        ],
      },
      DECLARATIONS_AUTHORIZATION_SECTION,
    ],
  },

  ANTNAS_2026: {
    title: 'Anticipo NASPI',
    description: 'Richiesta di liquidazione anticipata NASPI per avvio attività autonoma',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'documenti_richiesti',
        title: 'Documenti Richiesti',
        description: 'Carica i documenti necessari per la richiesta di anticipo NASPI',
        fields: [
          {
            name: 'documento_riconoscimento',
            label: 'Documento di riconoscimento',
            type: 'file',
            required: true,
            order: 1,
            description: 'Carta d\'identità fronte e retro, Patente fronte e retro, o Passaporto',
          },
          {
            name: 'codice_fiscale',
            label: 'Codice Fiscale',
            type: 'file',
            required: true,
            order: 2,
            description: 'Fronte e retro',
          },
          {
            name: 'permesso_soggiorno',
            label: 'Permesso di soggiorno del richiedente',
            type: 'file',
            required: false,
            order: 3,
            description: 'Obbligatorio se extracomunitario',
          },
          {
            name: 'certificato_piva',
            label: 'Certificato di attribuzione P.IVA',
            type: 'file',
            required: true,
            order: 4,
            description: 'Allega il certificato di attribuzione della Partita IVA',
          },
          {
            name: 'certificato_inizio_attivita',
            label: 'Certificato che attesta l\'inizio attività',
            type: 'file',
            required: true,
            order: 5,
            description: 'Visura camerale attiva, iscrizione gestione separata INPS, ecc.',
          },
        ],
      },
      DECLARATIONS_AUTHORIZATION_SECTION,
    ],
  },

  DID_2026: {
    title: 'DID - Dichiarazione di Immediata Disponibilità',
    description: 'Dichiarazione di immediata disponibilità al lavoro',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'documenti_richiesti',
        title: 'Documenti Richiesti',
        description: 'Carica i documenti necessari per la dichiarazione DID',
        fields: [
          {
            name: 'documento_riconoscimento',
            label: 'Documento di riconoscimento',
            type: 'file',
            required: true,
            order: 1,
            description: 'Carta d\'identità fronte e retro, Patente fronte e retro, o Passaporto',
          },
          {
            name: 'codice_fiscale',
            label: 'Codice Fiscale richiedente',
            type: 'file',
            required: true,
            order: 2,
            description: 'Fronte e retro',
          },
        ],
      },
      DECLARATIONS_AUTHORIZATION_SECTION,
    ],
  },

  PAD_2026: {
    title: 'PAD NASPI/DIS-COLL',
    description: 'Patto di Attivazione Digitale per beneficiari NASpI e DIS-COLL',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'documenti_richiesti',
        title: 'Documenti Richiesti',
        description: 'Carica i documenti necessari per il PAD',
        fields: [
          {
            name: 'carta_identita',
            label: 'Carta d\'identità',
            type: 'file',
            required: true,
            order: 1,
            description: 'Fronte e retro',
          },
          {
            name: 'codice_fiscale',
            label: 'Codice Fiscale',
            type: 'file',
            required: true,
            order: 2,
            description: 'Fronte e retro',
          },
        ],
      },
      {
        id: 'curriculum',
        title: 'Curriculum',
        description: 'Carica il tuo CV aggiornato',
        fields: [
          {
            name: 'cv_upload',
            label: 'CV (Curriculum Vitae)',
            type: 'file',
            required: true,
            order: 1,
            description: 'Allega CV aggiornato',
          },
        ],
      },
      DECLARATIONS_AUTHORIZATION_SECTION,
    ],
  },

  NASPICOM_2026: {
    title: 'NASPI-Com',
    description: 'Comunicazione variazione situazione NASPI',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'documenti_richiesti',
        title: 'Documenti Richiesti',
        description: 'Carica i documenti necessari per la comunicazione NASPI',
        fields: [
          {
            name: 'documento_riconoscimento',
            label: 'Documento di riconoscimento',
            type: 'file',
            required: true,
            order: 1,
            description: 'Carta d\'identità fronte e retro, Patente fronte e retro, o Passaporto',
          },
          {
            name: 'codice_fiscale',
            label: 'Codice Fiscale richiedente',
            type: 'file',
            required: true,
            order: 2,
            description: 'Fronte e retro',
          },
          {
            name: 'permesso_soggiorno',
            label: 'Permesso di soggiorno del richiedente',
            type: 'file',
            required: false,
            order: 3,
            description: 'Obbligatorio se extracomunitario',
          },
        ],
      },
      {
        id: 'variazione',
        title: 'Variazione',
        description: 'Documentazione della variazione della situazione lavorativa',
        fields: [
          {
            name: 'documentazione_variazione',
            label: 'UNILAV / Contratto di lavoro / Certificato di attività autonoma',
            type: 'file',
            required: true,
            order: 1,
            description: 'Allega il documento che attesta l\'inizio di attività lavorativa',
          },
        ],
      },
      DECLARATIONS_AUTHORIZATION_SECTION,
    ],
  },

  RICORSO_NASP_2026: {
    title: 'Ricorso NASPI',
    description: 'Ricorso avverso rigetto domanda NASPI',
    sections: [
      PERSONAL_INFORMATION_SECTION,
      {
        id: 'prove_ricorso',
        title: 'Le prove per Ricorso',
        description: 'Carica i documenti necessari per il ricorso NASPI',
        fields: [
          {
            name: 'lettera_rigetto',
            label: 'Lettera di Rigetto',
            type: 'file',
            required: true,
            order: 1,
            description: 'Allega la lettera di rigetto ricevuta dall\'INPS',
          },
          {
            name: 'lettera_licenziamento',
            label: 'Ultima Lettera di Licenziamento',
            type: 'file',
            required: true,
            order: 2,
            description: 'Allega l\'ultima lettera di licenziamento',
          },
        ],
      },
      DECLARATIONS_AUTHORIZATION_SECTION,
    ],
  },
};
